resources:

  psf_models:
    standard:
      inference_config: inference_standard.yaml
    oversampled:
      inference_config: inference_oversampled.yaml

metrics:

  mask_obscuration:
    enabled: true
    params:
      aperture: gaussian
      sigma: 2.5

  goodness_of_fit:
    enabled: true
    required_resources:
      - psf_models.standard
    params:
      statistic: reduced_chi_square
      normalize_residuals: true


rejection:

  mask_obscuration:
    enabled: true
    policy:
      threshold:
        value: 0.25

  goodness_of_fit:
    enabled: false
    policy:
      threshold:
        value: 3.0

reporting:

  save_metrics: true
  log_statistics: true