# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CD

on:
  push:
    branches:
      - main


jobs:
  docs:
    name: Deploy API documentation
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.5"
          
      - name: Check Python Version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install ".[docs]"
     
      - name: Build API documentation
        run: |
          sphinx-apidoc -Mfeo docs/source src/wf_psf
          sphinx-build docs/source docs/build
       
      - name: Deploy API documentation
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: docs/build
